# This is a basic workflow that is manually triggered

name: Install VerCors

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  compile_vercors:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    steps:
      - name: Clone VerCors
        uses: actions/checkout@v4
        with:
          repository: 'utwente-fmt/vercors'
          path: 'vercors'
          ref: 'AddSMTSolver'
      - name: Install Java
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
      - name: Cache dependencies and compilation
        uses: actions/cache@v4
        with:
          path: vercors/out
          key: vercors-ci-ubuntu-${{ hashFiles('vercors/build.sc') }}-${{ hashFiles('vercors/src') }}
          restore-keys: |
            vercors-ci-ubuntu-${{ hashFiles('build.sc') }}
            vercors-ci-ubuntu
      - name: Compile
        run: cd vercors && ./mill vercors.main.compile
          
  run_vercors:
    needs: "compile_vercors"
    runs-on: ubuntu-24.04
    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Get version
        run: ./vercors/bin/vct --version
